.gitignore
lib/api/media.ex
lib/parser.ex
lib/whatsapp_api.ex
test/api/media_test.exs

Based on the [WA Documentation](https://developers.facebook.com/docs/whatsapp/api/media), I've added support for deleting media on a WhatsApp instance

Support for deleting media

---

README.md
lib/api/users.ex
lib/whatsapp_api.ex
mix.exs

https://developers.facebook.com/docs/whatsapp/api/users/manage#create

Create Whatsapp User Support

---

README.md
mix.exs

- Mix and README should be updated to generate a hex.pm release correctly

Updates mix and README to 0.5.0

---

.ci.yml
README.md
mix.exs

En este cambio incluimos cambios para hacer el build, test y publish de el paquete usando drone.

Publicar paquetes a hexpm con drone

---

lib/api/messages.ex
lib/models/message_outbound_media_hsm_id.ex
lib/models/message_outbound_media_id_hsm.ex
lib/whatsapp_api.ex
mix.exs

Message of HSM media are implemented with JSON format

Implement hsm message with json

---

lib/models/message_outbound_media_id_hsm.ex
mix.exs

Se modifica validación de params en el envio de hsm json

Change validation params in hsm json

---

lib/api/messages.ex
lib/models/message_outbound_template.ex
lib/whatsapp_api.ex
mix.exs

Template messages are added to change  HSM messages for version 2.39 of whatsapp

Added template message

---

lib/models/message_outbound_hsm.ex
mix.exs

Se corrige la recepcion de parametros que recibe los mensajes de HSM

Fix parameter hsm

---

lib/models/message_outbound_media_id_hsm.ex
mix.exs

The filename object is added to the hsm id media in specific of type document

The filename object is added to the hsm id

---

lib/api/messages.ex
lib/models/message_outbound_hsm.ex
lib/models/message_outbound_media_general.ex
lib/models/message_outbound_media_id_hsm.ex
lib/whatsapp_api.ex

Se agrega modelo de mensajes multimedia solo con envio de id

Added message media

---

mix.exs

Se actualiza la version de la bibilioteca

Updated version

---

.github/workflows/elixir.yml
lib/api/messages.ex
lib/models/message_outbound_hsm_interactive.ex
lib/whatsapp_api.ex
mix.exs

Module is added for interactive template message

Added module template interactive message

---

lib/api/contacts.ex
lib/api/messages.ex
lib/auth/manager.ex
lib/auth/server.ex
lib/auth/token.ex
lib/models/whatsapp_provider.ex
mix.exs

Se maneja errores al solicitar token

Handle get token errors

---

lib/api/contacts.ex
lib/parser.ex
lib/whatsapp_api_base_request.ex
lib/whatsapp_api_request.ex
lib/whatsapp_api_request_media.ex
mix.exs
test/api/contacts_test.exs

- `WhatsappApiBaseRequest` -> Added a base module to handle requests and retries.
- Removed duplicated code in both `WhatsappApiRequest` and `WhatsappApiRequestMedia`, and updated to use the base module.
- Minor update in contact test

Improve requests to handle retries

---

lib/whatsapp_api_base_request.ex
lib/whatsapp_api_request_media.ex
mix.exs

- Added `delete!` method in the validation
- minor update in log message

Add missing delete! method and minor log update

---

lib/models/message_outbound_hsm.ex
lib/models/message_outbound_hsm_interactive.ex
lib/whatsapp_api_base_request.ex
mix.exs

- The json is modified for the optional header and footer component in HSM messages (text, multimedia, interactive)

Added optional components to hsm message and hsm interactive message

---

lib/models/message_outbound_media_id_hsm.ex
mix.exs

Component for dinamyc buttons is added to the multimedia HSM

Added functionality for hsm media dinamyc button

---

lib/models/message_outbound_media_id_hsm.ex
mix.exs

A fuction for performing pattern matching is  added to the components of the buttons in the multmedia HSM messages.

Updated version and add function components

---

lib/api/messages.ex
lib/models/message_outbound_hsm_otp.ex
lib/whatsapp_api.ex
mix.exs

It adds functionality for sending authentication messages with OTP template with option Copy Code button

Added authentication message template with OTP

---

.github/workflows/publish_hexpm.yml

The workflows configuration file for publishing to Hexpm is added.

Added workflow of publish hexpm

---

.github/workflows/publish_hexpm.yml

Runner is changed in the Workflows.

Changed run in workflow

---

lib/cloud_api/media.ex
mix.exs

fix(cloudapi/media): correct MIME type detection for audio, video, documents and stickers when uploading media

Fix mime type detection
